language: java
jdk:
- oraclejdk7
before_install:
- chmod +x gradlew
env:
  global:
  - secure: cnHZNJHntKFna4BAfdV1Dc53dHLvjY5TIcYeeVbMn84CgB4ieLYULoRYijMVeCy3y0R1VpZFUvViig8AaeJ5d95Wd8MJprRYC+3fxZD8QZBpwW0kvmfdrkpZsFvy9ekU4X4HPc2r3GMWCwzhXxjfUF99daPRtfZCRLz4iw+CIkdO+VA0OSeOKqq/tE2SpWwg9wOyEkvsonkiucTDoFS+HhqIZfTKIuRm05Bj4GG+jwjAMOmKtDFmzOnIsiaH6t/cM21O29nhdIrMyqAqH0UCG8DitNgPocigrCGm3ifQ9yGGZe4mwMtCKQwlrbuW77cB07EN7QikcQVZPhXkf3up/iKs8nh75hQ7BAeRkjJ5Psx7CY+iM7q6+CTln81gq0uvlHGECJ9izHMnWzqmCruCeaTUA4p2TBXwg8b9f/HtzlmmxODhBwgiZF9WDLlmsmo+uhv6LpHDBUhJMhU8pPkTO+n3pU7MAvaIf9ljmffxzRLaeb8xc92O2eJNXvE9WXjZPB7LkLsf+2vIDfNOMKAZqsCZ84XhGhZpIOsEjWedGVS1JVNayjkD7sXLprbGgf4V2h0hb1UGEN9APT+Gj6aWkXV4PiMU+r/a4/vnDm139cv/xvMgIs/7LEOjjKreFMcfucGlhcMKd7Mq4H+p7ab8zQ2WErSOHSWPsSKCJ8ybFTQ=
after_success:
- ./gradlew uploadArchives -PsonatypeUsername="${SONATYPE_USERNAME}" -PsonatypePassword="${SONATYPE_PASSWORD}" -i -s
