language: java
jdk:
- oraclejdk7
before_install:
- chmod +x gradlew
env:
  global:
  - secure: cnHZNJHntKFna4BAfdV1Dc53dHLvjY5TIcYeeVbMn84CgB4ieLYULoRYijMVeCy3y0R1VpZFUvViig8AaeJ5d95Wd8MJprRYC+3fxZD8QZBpwW0kvmfdrkpZsFvy9ekU4X4HPc2r3GMWCwzhXxjfUF99daPRtfZCRLz4iw+CIkdO+VA0OSeOKqq/tE2SpWwg9wOyEkvsonkiucTDoFS+HhqIZfTKIuRm05Bj4GG+jwjAMOmKtDFmzOnIsiaH6t/cM21O29nhdIrMyqAqH0UCG8DitNgPocigrCGm3ifQ9yGGZe4mwMtCKQwlrbuW77cB07EN7QikcQVZPhXkf3up/iKs8nh75hQ7BAeRkjJ5Psx7CY+iM7q6+CTln81gq0uvlHGECJ9izHMnWzqmCruCeaTUA4p2TBXwg8b9f/HtzlmmxODhBwgiZF9WDLlmsmo+uhv6LpHDBUhJMhU8pPkTO+n3pU7MAvaIf9ljmffxzRLaeb8xc92O2eJNXvE9WXjZPB7LkLsf+2vIDfNOMKAZqsCZ84XhGhZpIOsEjWedGVS1JVNayjkD7sXLprbGgf4V2h0hb1UGEN9APT+Gj6aWkXV4PiMU+r/a4/vnDm139cv/xvMgIs/7LEOjjKreFMcfucGlhcMKd7Mq4H+p7ab8zQ2WErSOHSWPsSKCJ8ybFTQ=
  - secure: C9RlC/5pKmWAJoNEqYRE3DJRkG5pikF/8lQXrxKl3F42vI+oMOQBkCKQ7nzhUlEcBFtWRw7eBiMonES/cz6PlUFeVBvID5/1iFBnwylahLcNnf6QU3DYUxFUaBFXhGz8rJfLW5YXzLbk/3uajJJ7LXXpAfZ8d7Rzht81bBKbNfdaRBw2rZ6qWpoyATp6Qe8OduOuNWXGDnIxYFDEqzBvCkPvYZfvsJNe//o8R4nZ8d+C4K+tEKEDCyz2LCeIyn5YFEP0jAIiX6hWnF2FeU6AsDrRbfjQQyG5obiybHn4lihbA+owLNTMx9nLsVLvAJ4YRIOjUy0/BEo3baL4qOvfLKJNcZX0Wlk/dG56YUgzfAFjLwGHa0mlzyMlILMxDN2T2W7i3toTLViBGPDk3N3Zj9a5TabjnzBRgcs1Toe0UdtnuCxDhCmy/5b8lTtHXFpZGuKKk4c8hTAmzk7AKnOERHXtsBuBDd/D90MAxHqr1b9MNmYV/tOpPYTv1fZ8wiHCceAUZZiJhpoEIjgw2nb2lmXxmf56604h1HR7vGUX+0kHIDE8yGmdJaW04vuP1iK6prqFilSzQteEjumoz45BpAdK7GPtRQlL0HyhBEx1esb6ys37XraBPe93Zglr6LKzb7P/2SEy72gDSqcUZU8Yyq3+7mOiqNxUfQgt6YFj/EM=
after_success:
- chmod +x ./deploy.sh; ./deploy.sh

