/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkPerry' at '26/07/15 12:01 AM' with Gradle 2.4
 *
 * @author MarkPerry, @date 26/07/15 12:01 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
